## QUESTÃO 01


Printe os elementos dos seguintes dois vetores usando apenas um for:

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

Depois, faça o mesmo usando numpy (usando a função nditer) e deixe um comentário sobre a diferença dos dois métodos.

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [5]:
#A MATRIZ TEM 3 DIMENSÕES. ESTOU TESTANDO COM 1 FOR
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in arr:
  print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [ ]:
# TESTANDO COM 2 FOR
for x in arr:
  for y in x:
    print(y)

In [ ]:
# TESTANDO COM 3 FOR

for x in arr:
    for y in x:
        for z in y:
            print(z) 

In [ ]:
# Usando o a função nditer

for i in np.nditer(arr):
    print(i)

#### RESPOSTA FINAL Q 1:

In [ ]:
import numpy as np
print('USANDO O FOR SEM FUNÇÕES:')
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in arr:
  for y in x:
    for z in y:
        print(z)
print("=" * 30)
print('USANDO A FUNÇÃO NDITER:')
for i in np.nditer(arr):
    print(i)


## QUESTÃO 02

Peça para o usuário uma lista com as comidas favoritas dele, depois transforme isso em um objeto numpy. Agora transformado, elimine todas as comidas que começam com uma vogal. Mostre o resultado.

Exemplo:

Entrada: [maçã, uva, morango, melancia, acelga]

Saída: [maçã, morango, melancia]

In [2]:
import numpy as np
from time import sleep

print('=' * 40)
print('LISTA DE COMIDAS PREFERIDAS'.center(40))
print('=' * 40)
sleep(0.5)

a = []
b = []
c = []
while True:
    a.append(input('Insira o nome de uma comida: '))
    exit = input('Deseja continuar?[S/N]: ').upper().split()[0]
    if exit in 'Nn':
        break
    while True:
        if exit not in 'SN':
            print('ERRO. Digite um valor válido')
            exit = input('Deseja continuar?[S/N]: ').upper().split()[0]
        else:
            break

for i in a:
    b = i[:1]
    if b not in 'AaEeIiOoUu':
        c.append(i)
print('*' * 50)
d = np.array(c)
print(f'A lista de todas as comidas é:\n{a}')
print('=' * 50)
print(f'A lista sem as que começam com vogal é:\n{d}')
print('=' * 50)
print(f'O tipo na nova lista é:\n{type(d)}')

      LISTA DE COMIDAS PREFERIDAS       
Insira o nome de uma comida: acerola
Deseja continuar?[S/N]: s
Insira o nome de uma comida: banana
Deseja continuar?[S/N]: s
Insira o nome de uma comida: maça
Deseja continuar?[S/N]: s
Insira o nome de uma comida: uva
Deseja continuar?[S/N]: t
ERRO. Digite um valor válido
Deseja continuar?[S/N]: e
ERRO. Digite um valor válido
Deseja continuar?[S/N]: n
Insira o nome de uma comida: Ameixa
Deseja continuar?[S/N]: N
**************************************************
A lista de todas as comidas é:
['acerola', 'banana', 'maça', 'uva', 'Ameixa']
A lista sem as que começam com vogal é:
['banana' 'maça']
O tipo na nova lista é:
<class 'numpy.ndarray'>


## QUESTÃO 03
Imprima a dimensão dos seguintes objetos numpy:

a = np.array(2)

b = np.array([1, 2, 3, 4, 5])

c = np.array([[1, 2, 3], [4, 5, 6]])

d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [8]:
import numpy as np
a = np.array(2)

b = np.array([1, 2, 3, 4, 5])

c = np.array([[1, 2, 3], [4, 5, 6]])

d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(f'O objeto A tem {a.ndim} dimensões.')
print(f'O objeto B tem {b.ndim} dimensões.')
print(f'O objeto C tem {c.ndim} dimensões.')
print(f'O objeto D tem {d.ndim} dimensões.')



O objeto A tem 0 dimensões.
O objeto B tem 1 dimensões.
O objeto C tem 2 dimensões.
O objeto D tem 3 dimensões.


## QUESTÃO 04
Transforme o array em uma matriz 4 por 3 utilizando numpy.

arr = [1, 2, 3, 4, 'Amelia, 'Bruna, 'Carolina', 'Débora', True, False, False, True]

Depois, faça o mesmo para uma matriz 3 por 4.

In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 'Amelia', 'Bruna', 'Carolina', 'Débora', True, False, False, True])

mat4_3 = arr.copy()
mat3_4 = arr.copy()

mat4_3 = arr.reshape(4, 3)
mat3_4 = arr.reshape(3, 4)

print(f'O array original é:\n {arr}')
print(f'A sua matriz é: {arr.shape}')
print('=' * 50)
print(f'O array 4 x 3 é:\n {mat4_3}')
print(f'A sua matriz é: {mat4_3.shape}')
print('=' * 50)
print(f'O array original é:\n {mat3_4}')
print(f'A sua matriz é: {mat3_4.shape}')

## QUESTÃO 05
Transforme o seguinte array em uma matriz 3D 3x3x3:

arr = range(27)

Deixe um comentário explicando o que significa uma matriz 3D.

In [8]:
import numpy as np
arr = np.array(27)
arr1 = np.full((3,3,3),27)
print(f'O array em matriz 3D é:\n{arr1}')
print(f'As dimensões do array modificado é:\n{arr1.ndim}')


O array em matriz 3D é:
[[[27 27 27]
  [27 27 27]
  [27 27 27]]

 [[27 27 27]
  [27 27 27]
  [27 27 27]]

 [[27 27 27]
  [27 27 27]
  [27 27 27]]]
As dimensões do array modificado é:
3


#### Uma matriz em 3D se trata de um conjunto tabular númerico em 3 dimensões, analogo aos 3 eixos x, y, z.

## QUESTÃO 06
Tente transformar o seguinte array em uma matriz 3x3x3

arr = [1, 2, 3, 4, 5, 6, 7, 8]

Funciona? Se sim, explique o motivo. Se não, explique o erro.

In [19]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
arr_ = arr.reshape(3,3,3)
print(f'{arr_.ndim}')
arr_ = arr.reshape(2,2,2)
print(f'{arr_.ndim}')


ValueError: cannot reshape array of size 8 into shape (3,3,3)

In [20]:
arr_ = arr.reshape(2,2,2)
print(f'{arr_.ndim}')

3


#### Não é possível transformar este array em uma matriz 3x3x3 devido ao fato de ele possuir somente 8 elementos. Para tal ele necessitaria ter 9 elementos. Em contrapartida é possível criar uma matriz 3D se usarmos uma formatação de 2x2x2

## QUESTÃO 07
Percorra o seguinte array utilizando for encaixado:

arr = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]

Agora, percorra o mesmo array utilizando a função nditer de numpy.

In [29]:
import numpy as np
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print('Utilizando o for encaixado:')
for x in arr:
    for y in x:
        for z in y:
            print(z)
print('=' * 30)
print('Utilizando o nditer:')
for i in np.nditer(arr):
    print(i)
            


Utilizando o for encaixado:
1
2
3
4
5
6
7
8
Utilizando o nditer:
1
2
3
4
5
6
7
8


## QUESTÃO 08
Percorra os indexes do seguinte array utilizando for encaixado:

arr = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]

Agora faça o mesmo trabalho utilizando a função ndenumerate.

In [30]:
import numpy as np
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print('Utilizando o for encaixado:')
for x in arr:
    for y in x:
        for z in y:
            print(z)
print('=' * 30)
print('Utilizando o ndenumerate:')
for i in np.ndenumerate(arr):
    print(i)

Utilizando o for encaixado:
1
2
3
4
5
6
7
8
Utilizando o ndenumerate:
((0, 0, 0), 1)
((0, 0, 1), 2)
((0, 1, 0), 3)
((0, 1, 1), 4)
((1, 0, 0), 5)
((1, 0, 1), 6)
((1, 1, 0), 7)
((1, 1, 1), 8)


## QUESTÃO 09
Junte os dois seguintes arrays na horizontal:

arr1 = [1, 2, 3]

arr2 = [4, 5, 6]

Depois, os junte verticalmente.

In [31]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

print(f'O empilhamento horizontal é:\n{np.hstack((arr1,arr2))}')
print('=' * 40)
print(f'O empilhamento vertical é:\n{np.vstack((arr1,arr2))}')

O empilhamento horizontal é:
[1 2 3 4 5 6]
O empilhamento vertical é:
[[1 2 3]
 [4 5 6]]


## QUESTÃO 10
DESAFIO: Utilizando manipulação de arrays, ache os indexes do array cujo valor possua apenas 2 vogais no nome usando numpy.

frutas = ['banana', 'morango, 'uva', 'pitaia', 'abacate', 'abacaxi', 'acerola', 'jenipapo', 'kiwi']

In [158]:
# Sem usar numpy
frutas1 = ['banana', 'morango', 'uva', 'pitaia', 'abacate', 'abacaxi', 'acerola', 'jenipapo', 'kiwi']

a = []
b = int()
c = []

for i in frutas1:
    for x in i:
        if x in 'AaEeIiOoUu':
            b += 1
    if b == 2:
        c.append(i)
    b = 0
            
print('*' * 50)
print(f'A lista de palavras com apenas 2 vogais é:\n{c}')


**************************************************
A lista de palavras com apenas 2 vogais é:
['uva', 'kiwi']


In [193]:
# Usando Numpy
import numpy as np

def sep_arr(a):
    b = int()
    c = []
    for i in a:
        for x in i:
            if x in 'AaEeIiOoUu':
                b += 1
        if b == 2:
            c.append(i)
        b = 0
    return c
    
frutas = np.array(['banana', 'morango', 'uva', 'pitaia', 'abacate', 'abacaxi', 'acerola', 'jenipapo', 'kiwi'])
sep_arr(frutas)


TypeError: 'numpy.dtype[str_]' object is not callable

## QUESTÃO 11
a) Tranforme o seguinte array 2D em dois arrays 2D:

arr = [[1, 2], [3, 4], [5, 6], [7, 8]]

b) Transforme o seguinte array em três arrays com apenas uma coluna:

arr = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

### A)

In [33]:
#A)
import numpy as np
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
b = arr.reshape(2,2,2)
print(b)
print(b.shape)


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)


### B)

In [35]:
#B)
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = arr.reshape(3,3,1)
print(b)
print(b.shape)

[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]

 [[7]
  [8]
  [9]]]
(3, 3, 1)


## QUESTÃO 12
DESAFIO: Utilizando manipulação de arrays, vamos seguir um conjunto de passos para organizar alguns dados. Teremos nesse seguinte array uma ordem que segue:

[Nome do aluno, idade, 'gênero', signo, altura, nota do 1° semestre, nota do 2° bimestre, se está ou não inscrito no próximo ano da escola, nome do outro aluno, idade do outro aluno...]

arr = ['Amélia', 13, 'F', 'peixes', 1.51, 9, 7, True, 'Bruno', 14, 'O', 'leão', 1.60, 4, 10, False, 'João', 14, 'M', 'escorpião', 1.58, 8, 9, True, 'Jordana', 13, 'F', 'escorpião', 1.72, 9, 9, False]

a) Enumere os indexes de todas as informações que são do tipo string.

b) Separe essas informações do objeto arr de forma que cada aluno tenha seu próprio array.

c) Separe em duas colunas, a primeira com o nome, a idade, o gênero e o signo e a segunda com a altura, nota do primeiro bimestre, nota do segundo bimestre e se está ou não inscrito no próximo ano.

d) Elimine o gênero de todos os arrays cujos alunos tem menos de 14 anos.

### A) Enumere os indexes de todas as informações que são do tipo string.

In [44]:
arr = np.array(['Amélia', 13, 'F', 'peixes', 1.51, 9, 7, True, 
                'Bruno', 14, 'O', 'leão', 1.60, 4, 10, False, 
                'João', 14, 'M', 'escorpião', 1.58, 8, 9, True, 
                'Jordana', 13, 'F', 'escorpião', 1.72, 9, 9, False])

# a)
indices = np.where(np.char.isalpha(arr))[0]
print(indices)
print('=' * 50)


[ 0  2  3  7  8 10 11 15 16 18 19 23 24 26 27 31]


### B) Separe essas informações do objeto arr de forma que cada aluno tenha seu próprio array.

In [45]:
# b)
alunos = np.split(arr, 4) # o número se refere a qtd de divisões
for i in alunos:
    print(i)
print('=' * 55)

['Amélia' '13' 'F' 'peixes' '1.51' '9' '7' 'True']
['Bruno' '14' 'O' 'leão' '1.6' '4' '10' 'False']
['João' '14' 'M' 'escorpião' '1.58' '8' '9' 'True']
['Jordana' '13' 'F' 'escorpião' '1.72' '9' '9' 'False']


### C) Separe em duas colunas, a primeira com o nome, a idade, o gênero e o signo e a segunda com a altura, nota do primeiro bimestre, nota do segundo bimestre e se está ou não inscrito no próximo ano.

In [46]:
## c)
coluna1, coluna2 = np.hsplit(arr.reshape(-1, 8), 2)
print(coluna1)
print(coluna2)
print('=' * 35)
# Também pode ser feito assim:
alunos = np.split(arr, 8) # o número se refere a qtd de divisões
for i in alunos:
    print(i)
print('=' * 35)

[['Amélia' '13' 'F' 'peixes']
 ['Bruno' '14' 'O' 'leão']
 ['João' '14' 'M' 'escorpião']
 ['Jordana' '13' 'F' 'escorpião']]
[['1.51' '9' '7' 'True']
 ['1.6' '4' '10' 'False']
 ['1.58' '8' '9' 'True']
 ['1.72' '9' '9' 'False']]
['Amélia' '13' 'F' 'peixes']
['1.51' '9' '7' 'True']
['Bruno' '14' 'O' 'leão']
['1.6' '4' '10' 'False']
['João' '14' 'M' 'escorpião']
['1.58' '8' '9' 'True']
['Jordana' '13' 'F' 'escorpião']
['1.72' '9' '9' 'False']


### D) Elimine o gênero de todos os arrays cujos alunos tem menos de 14 anos.

In [48]:
# d)
def delete_gender(x):
    if int(x[1]) < 14:
        x[2] = None
    return x

sem_genero = np.apply_along_axis(delete_gender, axis=1, arr=coluna1)
print(sem_genero)
print('=' * 50)

[['Amélia' '13' 'None' 'peixes']
 ['Bruno' '14' 'O' 'leão']
 ['João' '14' 'M' 'escorpião']
 ['Jordana' '13' 'None' 'escorpião']]
