In [ ]:
import numpy as np

In [ ]:
arr = range(27)
arr

In [ ]:
# QUESTÃO 06 NUMPY
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
b  = arr.reshape(3,3,3)

### NÃO É POSSÍVEL FORMAR UMA MATRIZ 3 X 3 X 3 POIS O ARRAY TEM SOMENTE 8 ELEMENTOS, A MATRIZ NESSE FORMATO NECESSITA SER DE 9 ELEMENTOS. COM ESSA QUANTIDADE DE STRINGS É POSSIVEL FAZER SOMENTE UMA MATRIZ 2 X 2 X 2

In [ ]:
# QUESTÃO 07

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print('A lista com for encadeado:')
for x in arr:
    for y in x:
        for z in y:
         print(z)   
print('=' * 40)
print('A lista com o nditer:')
for x in np.nditer(arr):
      print(x)

In [ ]:
# Questão 08

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print('A lista com for encadeado:')
for x in arr:
    for y in x:
        for z in y:
         print(z)   
print('=' * 40)
print('A lista com o ndenumerate:')
for x in np.ndenumerate(arr):
      print(x)

In [ ]:
# Questão 09
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

print(f'O empilhamento horizontal é:\n{np.hstack((arr1,arr2))}')
print('=' * 40)
print(f'O empilhamento vertical é:\n{np.vstack((arr1,arr2))}')

In [45]:
# Questão 10
# DESAFIO: Utilizando manipulação de arrays, ache os indexes do array cujo valor possua apenas 2 vogais no nome usando numpy.
import numpy as np
frutas = np.array(['banana', 'morango', 'uva', 'pitaia', 'abacate', 'abacaxi', 'acerola', 'jenipapo', 'kiwi'])
f2 = []
cont = 0
for i in frutas:
    teste = i.find('a')
    if teste:
        alt_a = i.replace('a', '1')
    print(alt_a)
    #if i in "a":
       # a = i.count("a")
        #cont += a
        #e = i.count("e")
        #cont += e
        #i = i.count("i")
        #cont += i
        #o = i.count("o")
        #cont += o
        #u = i.count("u")
        #cont += u
        #if a  == 2:
            #f2.append(frutas[i])
    #print(a)

b1n1n1
mor1ngo
uv1
pit1i1
pit1i1
pit1i1
pit1i1
jenip1po
kiwi


Questão #11
Vale10
Enunciado

a) Tranforme o seguinte array 2D em dois arrays 2D:

    arr = [[1, 2], [3, 4], [5, 6], [7, 8]]

b) Transforme o seguinte array em três arrays com apenas uma coluna:

    arr = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]



In [9]:
# a)
import numpy as np
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
b = arr.reshape(2,2,2)
print(b)
print(b.shape)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)


In [12]:
# b)
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = arr.reshape(3,3,1)
print(b)

[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]

 [[7]
  [8]
  [9]]]


Enunciado

DESAFIO: Utilizando manipulação de arrays, vamos seguir um conjunto de passos para organizar alguns dados. Teremos nesse seguinte array uma ordem que segue:

    [Nome do aluno, idade, 'gênero', signo, altura, nota do 1° semestre, nota do 2° bimestre, se está ou não inscrito no próximo ano da escola, nome do outro aluno, idade do outro aluno...]

    arr = ['Amélia', 13, 'F', 'peixes', 1.51, 9, 7, True, 'Bruno', 14, 'O', 'leão', 1.60, 4, 10, False, 'João', 14, 'M', 'escorpião', 1.58, 8, 9, True, 'Jordana', 13, 'F', 'escorpião', 1.72, 9, 9, False]

a) Enumere os indexes de todas as informações que são do tipo string.

b) Separe essas informações do objeto arr de forma que cada aluno tenha seu próprio array.

c) Separe em duas colunas, a primeira com o nome, a idade, o gênero e o signo e a segunda com a altura, nota do primeiro bimestre, nota do segundo bimestre e se está ou não inscrito no próximo ano.

d) Elimine o gênero de todos os arrays cujos alunos tem menos de 14 anos.


In [27]:
arr = np.array(['Amélia', 13, 'F', 'peixes', 1.51, 9, 7, True, 
                'Bruno', 14, 'O', 'leão', 1.60, 4, 10, False, 
                'João', 14, 'M', 'escorpião', 1.58, 8, 9, True, 
                'Jordana', 13, 'F', 'escorpião', 1.72, 9, 9, False])

# a)
indices = np.where(np.char.isalpha(arr))[0]
print(indices)
print('=' * 50)
# b)
alunos = np.split(arr, 4) # o número se refere a qtd de divisões
for i in alunos:
    print(i)
print('=' * 50)

# c)
coluna1, coluna2 = np.hsplit(arr.reshape(-1, 8), 2)
print(coluna1)
print(coluna2)
print('=' * 50)
# Também pode ser feito assim:
alunos = np.split(arr, 8) # o número se refere a qtd de divisões
for i in alunos:
    print(i)
print('=' * 50)
# d)
def delete_gender(x):
    if int(x[1]) < 14:
        x[2] = None
    return x

sem_genero = np.apply_along_axis(delete_gender, axis=1, arr=coluna1)
print(sem_genero)
print('=' * 50)


[ 0  2  3  7  8 10 11 15 16 18 19 23 24 26 27 31]
['Amélia' '13' 'F' 'peixes' '1.51' '9' '7' 'True']
['Bruno' '14' 'O' 'leão' '1.6' '4' '10' 'False']
['João' '14' 'M' 'escorpião' '1.58' '8' '9' 'True']
['Jordana' '13' 'F' 'escorpião' '1.72' '9' '9' 'False']
[['Amélia' '13' 'F' 'peixes']
 ['Bruno' '14' 'O' 'leão']
 ['João' '14' 'M' 'escorpião']
 ['Jordana' '13' 'F' 'escorpião']]
[['1.51' '9' '7' 'True']
 ['1.6' '4' '10' 'False']
 ['1.58' '8' '9' 'True']
 ['1.72' '9' '9' 'False']]
['Amélia' '13' 'F' 'peixes']
['1.51' '9' '7' 'True']
['Bruno' '14' 'O' 'leão']
['1.6' '4' '10' 'False']
['João' '14' 'M' 'escorpião']
['1.58' '8' '9' 'True']
['Jordana' '13' 'F' 'escorpião']
['1.72' '9' '9' 'False']
[['Amélia' '13' 'None' 'peixes']
 ['Bruno' '14' 'O' 'leão']
 ['João' '14' 'M' 'escorpião']
 ['Jordana' '13' 'None' 'escorpião']]
